[project]
name = "ai-agents"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.0.0",
    "langchain-ollama>=1.0.0",
    "ollama>=0.6.0",
]
